<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resourcies\Screenshot 2025-06-08 125713.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resourcies\Screenshot 2025-06-08 125713.png" />
  </ItemGroup>

</Project>
